redis:
  host: "127.0.0.1"
  port: 6379
  password:
http-port: 8080
minimal-key-length: 4
config-reload-time: 60
expected-stripes-per-hour: 1000
allowed-bad-attempts: 5
appropriate-chance-to-guess: 1000000000
password-policy: "allowed"
require-api-key: false
require-api-key-for-post-only: true
allowed-shares-period: 60
allowed-shares-number-in-period: 5
allowed-api-keys:
public-name: "Zebra Sharing Service"
public-color: "#000000"
public-url: "https://127.0.0.1"
extended-logs: false